update_ip:
  name: Update IP Address
  description: Cập nhật địa chỉ IP mới cho máy in Elegoo (khi máy in đổi IP).
  fields:
    entry_id:
      name: Config Entry
      description: Chọn máy in Elegoo mà bạn muốn cập nhật IP.
      required: true
      selector:
        config_entry:
          integration: elegoo_printer
    ip_address:
      name: IP Address
      description: Nhập địa chỉ IP mới của máy in (ví dụ 192.168.1.3).
      example: "192.168.1.3"
      required: true
      selector:
        text:
