update_ip:
  name: Update IP Address
  description: Update new IP adress.
  fields:
    entry_id:
      name: Config Entry
      description: Chooose printer need to change IP.
      required: true
      selector:
        config_entry:
          integration: elegoo_printer
    ip_address:
      name: IP Address
      description: Type ip adress that need to change (Example: 192.168.1.3).
      example: "192.168.1.3"
      required: true
      selector:
        text:
