blueprint:
  name: Elegoo Printer Progress Notification (v3)
  description: Sends a notification with the progress of an Elegoo printer.
  author: Daniel Cherubini
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  input:
    percent_complete_entity:
      name: Percent Complete Entity
      description: The percent complete sensor for the Elegoo printer (look for entities ending in '_percent_complete').
      selector:
        entity:
          domain: sensor
          integration: elegoo_printer
    notify_device:
      name: Notification Device
      description: The device to send notifications to.
      selector:
        device:
          integration: mobile_app
    percentage_divisor:
      name: Notification Frequency
      description: >-
        Notify when the percentage complete is divisible by this number. Use 1
        to be notified on every percentage change.
      selector:
        select:
          options:
            - "1"
            - "2"
            - "5"
      default: "5"
    camera_entity:
      name: Printer Camera (Optional)
      description: Override the default camera entity for the printer. Leave blank to use the default camera from the printer device.
      default: ""
      selector:
        entity:
          domain: camera
    dashboard_url:
      name: Dashboard URL (Optional)
      description: The path to open when the notification is clicked (e.g., '/dashboard-example/example', not the full URL).
      default: ""

mode: single
max_exceeded: silent

variables:
  percent_complete_entity: !input percent_complete_entity
  notify_device: !input notify_device
  percentage_divisor: !input percentage_divisor
  camera_entity_input: !input camera_entity
  dashboard_url: !input dashboard_url
  # Get the device from the percent complete entity
  printer_device: >-
    {{ device_id(percent_complete_entity) }}
  notification_group: >-
    {{ device_attr(printer_device, 'name') | slugify }}
  # Get other entities from the same device
  end_time_entity: >-
    {{ device_entities(printer_device) | select('search', '_end_time') |
    first }}
  file_name_entity: >-
    {{ device_entities(printer_device) | select('search', '_file_name') |
    first }}
  current_status_entity: >-
    {{ device_entities(printer_device) | select('search', '_current_status') |
    first }}
  current_layer_entity: >-
    {{ device_entities(printer_device) | select('search', '_current_layer') |
    first }}
  total_layers_entity: >-
    {{ device_entities(printer_device) | select('search', '_total_layers') |
    first }}
  camera_entity: >-
    {{ (camera_entity_input
        if camera_entity_input != ''
        else (device_entities(printer_device) | select('match', '^camera\.') | first))
       | default('', true) }}
  print_status_entity: >-
    {{ device_entities(printer_device) | select('search', '_print_status') |
    first }}

trigger:
  - platform: state
    entity_id: !input percent_complete_entity

condition: []

action:
  - if:
      - condition: template
        value_template: "{{ states(percent_complete_entity) | int < 100 }}"
    then:
      - if:
          - condition: template
            value_template: >-
              {{ states(percent_complete_entity) | int % (percentage_divisor | int) == 0 }}
          - condition: template
            value_template: >-
              {{ current_status_entity != none and states(current_status_entity) == 'printing' }}
          - condition: template
            value_template: "{{ notify_device != '' }}"
        then:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: "Printing: {{ states(percent_complete_entity) }}%\nLayer: {{ (states(current_layer_entity)|default('?', true)) }}/{{ (states(total_layers_entity)|default('?', true)) }}"
            message: "{{ states(file_name_entity)|default('Unknown file', true) }}"
            data:
              chronometer: true
              when: "{{ as_timestamp(states(end_time_entity))|int if end_time_entity != none and states(end_time_entity) not in ['unknown', 'unavailable'] else 0 }}"
              progress: "{{ states(percent_complete_entity)|int }}"
              progress_max: 100
              image: "{{ ('/api/camera_proxy/' ~ camera_entity) if (camera_entity|default('', true)) != '' else '' }}"
              url: "{{ dashboard_url }}"
              clickAction: "{{ dashboard_url }}"
              group: "{{ notification_group }}"
              channel: "{{ notification_group }}"
              tag: "{{ notification_group }}"
              alert_once: true
              sticky: true
    else:
      - if:
          - condition: template
            value_template: "{{ notify_device != '' }}"
          - condition: template
            value_template: "{{ print_status_entity != none and states(print_status_entity) == 'complete' }}"
        then:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            message: Print has finished
            data:
              url: "{{ dashboard_url }}"
              clickAction: "{{ dashboard_url }}"
              group: "{{ notification_group }}"
              channel: "{{ notification_group }}"
              tag: "{{ notification_group }}"
              sticky: true
              alert_once: false
