
blueprint:
  name: Elegoo Printer Progress Notification
  description: Sends a notification with the progress of an Elegoo printer.
  author: Daniel Cherubini
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  input:
    percent_complete_sensor:
      name: Percent Complete Sensor
      description: The printer's percent complete sensor.
      selector:
        entity:
          domain: sensor
          integration: elegoo_printer
    notify_device:
      name: Notification Device
      description: The device to send notifications to.
      selector:
        device:
          integration: mobile_app
    percentage_divisor:
      name: Notification Frequency
      description: >-
        Notify when the percentage complete is divisible by this number. Use 1
        to be notified on every percentage change.
      selector:
        select:
          options:
            - "1"
            - "2"
            - "5"
      default: "5"
    camera_entity:
      name: Printer Camera
      description: The camera entity for the printer.
      selector:
        entity:
          domain: camera
    dashboard_url:
      name: Dashboard URL (Optional)
      description: The URL to open when the notification is clicked.
      default: ""
    notification_group:
      name: Notification Group
      description: A unique name for the notification group, channel, and tag.
      default: "elegoo-printer"

mode: single
max_exceeded: silent

variables:
  percent_complete_entity: !input percent_complete_sensor
  elegoo_printer_device: "{{ device_id(percent_complete_entity) }}"
  notify_device: !input notify_device
  percentage_divisor: !input percentage_divisor
  camera_entity: !input camera_entity
  dashboard_url: !input dashboard_url
  notification_group: !input notification_group
  file_name_entity: >-
    {{ device_entities(elegoo_printer_device) | select('search', '_file_name') |
    first }}
  remaining_print_time_entity: >-
    {{ device_entities(elegoo_printer_device) | select('search',
    '_remaining_print_time') | first }}

trigger:
  - platform: state
    entity_id: !input percent_complete_sensor

condition: []

action:
  - if:
      - condition: numeric_state
        entity_id: !input percent_complete_sensor
        below: 100
    then:
      - if:
          - condition: template
            value_template: >-
              {{ states(percent_complete_entity) | int % (percentage_divisor | int) == 0 }}
          - condition: template
            value_template: "{{ notify_device != '' }}"
        then:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: "Printing: {{ states(percent_complete_entity) }}%"
            message: "{{ states(file_name_entity) }}"
            data:
              chronometer: true
              when: "{{ (states(remaining_print_time_entity)|float * 60)|int }}"
              when_relative: true
              progress: "{{ states(percent_complete_entity)|int }}"
              progress_max: 100
              image: "/api/camera_proxy/{{ camera_entity }}"
              url: "{{ dashboard_url }}"
              clickAction: "{{ dashboard_url }}"
              group: "{{ notification_group }}"
              channel: "{{ notification_group }}"
              tag: "{{ notification_group }}"
              alert_once: true
              sticky: true
    else:
      - if:
          - condition: template
            value_template: "{{ notify_device != '' }}"
        then:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            message: Print has finished
            data:
              url: "{{ dashboard_url }}"
              clickAction: "{{ dashboard_url }}"
              group: "{{ notification_group }}"
              channel: "{{ notification_group }}"
              tag: "{{ notification_group }}"
              sticky: true
              alert_once: false
