blueprint:
  name: Elegoo Printer Progress Notification (v3)
  description: Sends a notification with the progress of an Elegoo printer.
  author: Daniel Cherubini
  homeassistant:
    min_version: 2024.6.0
  domain: automation
  input:
    printer_device:
      name: Elegoo Printer Device
      description: The Elegoo printer device to monitor.
      selector:
        device:
          integration: elegoo_printer
    notify_device:
      name: Notification Device
      description: The device to send notifications to.
      selector:
        device:
          integration: mobile_app
    percentage_divisor:
      name: Notification Frequency
      description: >-
        Notify when the percentage complete is divisible by this number. Use 1
        to be notified on every percentage change.
      selector:
        select:
          options:
            - "1"
            - "2"
            - "5"
      default: "5"
    camera_entity:
      name: Printer Camera (Optional)
      description: Override the default camera entity for the printer. Leave blank to use the default camera from the printer device.
      default: ""
      selector:
        entity:
          domain: camera
    dashboard_url:
      name: Dashboard URL (Optional)
      description: The path to open when the notification is clicked (e.g., '/dashboard-example/example', not the full URL).
      default: ""

mode: single
max_exceeded: silent

variables:
  elegoo_printer_device: !input printer_device
  notify_device: !input notify_device
  percentage_divisor: !input percentage_divisor
  camera_entity_input: !input camera_entity
  dashboard_url: !input dashboard_url
  notification_group: >-
    {{ device_attr(elegoo_printer_device, 'name') | lower | replace(' ', '-') | replace('_', '-') }}
  percent_complete_entity: >-
    {{ device_entities(elegoo_printer_device) | select('search', '_percent_complete') |
    first }}
  remaining_print_time_entity: >-
    {{ device_entities(elegoo_printer_device) | select('search', '_remaining_print_time') |
    first }}
  file_name_entity: >-
    {{ device_entities(elegoo_printer_device) | select('search', '_file_name') |
    first }}
  current_status_entity: >-
    {{ device_entities(elegoo_printer_device) | select('search', '_current_status') |
    first }}
  camera_entity: >-
    {{ camera_entity_input if camera_entity_input != '' else 
       (device_entities(elegoo_printer_device) | select('match', 'camera\.') | first) }}
  print_status_entity: >-
    {{ device_entities(elegoo_printer_device) | select('search', '_print_status') |
    first }}

trigger:
  - platform: device
    device_id: !input printer_device
    domain: sensor
    type: state_changed

condition:
  - condition: template
    value_template: "{{ trigger.entity_id == percent_complete_entity }}"

action:
  - if:
      - condition: template
        value_template: "{{ states(percent_complete_entity) | int < 100 }}"
    then:
      - if:
          - condition: template
            value_template: >-
              {{ states(percent_complete_entity) | int % (percentage_divisor | int) == 0 }}
          - condition: template
            value_template: >-
              {{ states(current_status_entity) == 'printing' }}
          - condition: template
            value_template: "{{ notify_device != '' }}"
        then:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: "Printing: {{ states(percent_complete_entity) }}%"
            message: "{{ states(file_name_entity) }}"
            data:
              chronometer: true
              when: "{{ (states(remaining_print_time_entity)|float(0) * 60)|int }}"
              when_relative: true
              progress: "{{ states(percent_complete_entity)|int }}"
              progress_max: 100
              image: "/api/camera_proxy/{{ camera_entity }}"
              url: "{{ dashboard_url }}"
              clickAction: "{{ dashboard_url }}"
              group: "{{ notification_group }}"
              channel: "{{ notification_group }}"
              tag: "{{ notification_group }}"
              alert_once: true
              sticky: true
    else:
      - if:
          - condition: template
            value_template: "{{ notify_device != '' }}"
          - condition: template
            value_template: "{{ states(print_status_entity) == 'complete' }}"
        then:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            message: Print has finished
            data:
              url: "{{ dashboard_url }}"
              clickAction: "{{ dashboard_url }}"
              group: "{{ notification_group }}"
              channel: "{{ notification_group }}"
              tag: "{{ notification_group }}"
              sticky: true
              alert_once: false
